import type { Metadata } from 'next';
import { Roboto, Roboto_Condensed } from 'next/font/google';
import './globals.css';
import HeaderComponent from '@/components/header';
import FooterComponent from '@/components/footer';

const robottoSans = Roboto({
  variable: '--font-robotto-sans',
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900']
});

const robotto_Cond_Sans = Roboto_Condensed({
  variable: '--font-robotto-cond-sans',
  subsets: ['latin'],
  weight: ['900']
});

export const metadata: Metadata = {
  title: 'BetoFoxNet_Info Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-BR'>
      <body
        className={`${robottoSans.variable} ${robotto_Cond_Sans.variable} antialiased`}
      >
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}